[build-system]
requires = ["setuptools>=83"]
build-backend = "setuptools.build_meta"

[project]
name = "tunsberg"
dynamic = ["version"]
description = "A collection of opinionated methods, functions, classes and utils for Python, FastAPI and related libraries."
readme = "README.md"
requires-python = ">=3.11"
license = "MIT"
authors = [{ name = "Kilobyte AS" }]
dependencies = [
    "fastapi>=0.141.1",
    "starlette>=1.3.1",
    "pydantic>=2.13.4",
    "fastapi-pagination>=0.15.16",
]
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]

[project.urls]
Homepage = "https://github.com/kilobyteno/tunsberg"
Github = "https://github.com/kilobyteno/tunsberg"

[dependency-groups]
dev = [
    "pre-commit>=4.6.1",
    "ruff>=0.16.1",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "pytest-sugar>=1.1.1",
]

[tool.setuptools.packages.find]
include = ["tunsberg*"]

[tool.setuptools.dynamic]
version = { attr = "tunsberg.__version__" }

[tool.ruff]
line-length = 160
# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
    "alembic",
]

[tool.ruff.lint]
select = [
    "RUF", # ruff
    "E", "W", # pycodestyle
    "F", # Pyflakes
    "UP", # pyupgrade
    "B", # flake8-bugbear
    "SIM", # flake8-simplify
    "I", # isort
    "T", # flake8-print
    "TD", # flake8-todos
    "LOG", # flake8-logging
    "N", # pep8-naming
    "D", # pydocstyle
    "RET", # flake8-return
    "TYP", # flake8-type-checking
    "PL", # pylint
]
ignore = [
    "D100", # Missing docstring in public module
    "D101", # Missing docstring in public class
    "D102", # Missing docstring in public method
    "D104", # Missing docstring in public package
    "D415", # First line should end with a period
    "D203", # 1 blank line required before class docstring
    "D212", # Multi-line docstring summary should start at the first line
    "D400", # First line should end with a period
    "TD003", # Missing issue link on the line following
    "B008", # Do not perform function calls in argument defaults
]


[tool.ruff.format]
quote-style = "single"
indent-style = "space"
docstring-code-format = true


[tool.pytest.ini_options]
addopts = ["--disable-pytest-warnings", "--cov=tunsberg", "--cov-report=xml", "--cov-report=term-missing", "--cov-fail-under=90" ]
testpaths = ["tests"]
