name: "Code Style"

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - synchronize
      - opened
      - edited

jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10", "3.11", "3.12" ]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip' # caching pip dependencies
      - name: Install All Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Run Ruff
        run: ruff check --output-format=github
      - name: Check for vulnerabilities
        uses: pypa/gh-action-pip-audit@v1.1.0
        with:
          inputs: requirements.txt
      - name: Run Tests
        run: |
          pytest
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
